# Generated by Django 3.2.9 on 2021-12-17 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_auto_20211216_2302'),
        ('api', '0002_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Value')),
                ('function', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='D', max_length=1, verbose_name='Function')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
