# Generated by Django 3.2.9 on 2021-12-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211216_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='function',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='value',
        ),
    ]
