# Generated by Django 3.2.9 on 2021-12-17 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_account_cvv'),
        ('api', '0007_auto_20211216_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='function',
            field=models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='D', max_length=1, verbose_name='Function'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Value'),
        ),
    ]
