# Generated by Django 3.2.9 on 2021-12-17 00:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999999999)], verbose_name='Number')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('validity', models.DateField(auto_now=True, verbose_name='Validity')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Balance')),
                ('limit', models.DecimalField(decimal_places=2, default=100, max_digits=19, verbose_name='Limite')),
                ('cvv', models.CharField(max_length=255, verbose_name='Card Verification Value')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999)])),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Banks',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Value')),
                ('function', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='D', max_length=1, verbose_name='Function')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='accounts.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='accounts.bank'),
        ),
    ]
