# Generated by Django 3.2.9 on 2021-12-17 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211216_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(111), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
