# Generated by Django 3.2.9 on 2021-12-17 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_bank_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Number'),
        ),
    ]
