# Generated by Django 3.2.9 on 2021-12-17 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\d{16}$', message='Enter numbers only')], verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}$', message='Enter numbers only')], verbose_name='Number'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
