# Generated by Django 3.2.9 on 2021-12-17 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211216_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cvv',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', message='Enter only 4 numbers')], verbose_name='Card Verification Value'),
        ),
    ]
